version: '3.8'

services:
  # Serviço da API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço de workers
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped
    deploy:
      replicas: 2  # Número de instâncias do worker

  # Você poderia adicionar um banco de dados aqui se necessário
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_PASSWORD=secret
  #     - POSTGRES_USER=banquete
  #     - POSTGRES_DB=banquete
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data: